airflow_dbt:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      pass: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DBT_POSTGRES_DB') }}"
      schema: airflow
      threads: 4
